# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{orange-sparkles}
  s.version = "0.6.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Haslem"]
  s.date = %q{2010-07-07}
  s.description = %q{This gem is a }
  s.email = %q{therabidbanana@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/orange-sparkles.rb"
  ]
  s.homepage = %q{http://github.com/orange-project/orange-sparkles}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Adding some prettiness to orange-core}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<orange-core>, [">= 0.5.7"])
      s.add_runtime_dependency(%q<orange-more>, [">= 0.5.7"])
      s.add_runtime_dependency(%q<maruku>, [">= 0"])
      s.add_runtime_dependency(%q<rack-abstract-format>, [">= 0"])
    else
      s.add_dependency(%q<orange-core>, [">= 0.5.7"])
      s.add_dependency(%q<orange-more>, [">= 0.5.7"])
      s.add_dependency(%q<maruku>, [">= 0"])
      s.add_dependency(%q<rack-abstract-format>, [">= 0"])
    end
  else
    s.add_dependency(%q<orange-core>, [">= 0.5.7"])
    s.add_dependency(%q<orange-more>, [">= 0.5.7"])
    s.add_dependency(%q<maruku>, [">= 0"])
    s.add_dependency(%q<rack-abstract-format>, [">= 0"])
  end
end

